### ISSUE TITLE
没有办法下载

### ISSUE THREAD

**Issue by yangchongduo** [summerwind/sasazka#1]
npm 不行
  nodeHttp2 npm i --save sasazka
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/yangchongduo/.nvm/versions/node/v6.10.2/bin/node" "//.nvm/versions/node/v6.10.2/bin/npm" "i" "--save" "sasazka"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npm.taobao.org/sasazka
npm ERR! 404
npm ERR! 404  'sasazka' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Documents/nodeHttp2/npm-debug.log

**Comment by okuryu** [comment]
See: https://github.com/summerwind/sasazka#notes
> This is an experimental module. so this module is not registered on the npm registry yet.

**Comment by summerwind** [comment]
Sasazka have been deprecated. I recommend to use [node-http2](https://github.com/molnarg/node-http2).
@okuryu Thank you for the quick follow up!
